services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    command: sleep infinity
    depends_on:
      - db
  db:
    image: postgres:18.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5432:5432"